// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CoreOperationDummyFactory.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.CoreOperation.Test source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.CoreOperation.Test
{
    using global::System;

    using FakeItEasy;

    using OBeautifulCode.AutoFakeItEasy;

    /// <summary>
    /// A Dummy Factory for types in <see cref="OBeautifulCode.CoreOperation"/>.
    /// </summary>
#if !OBeautifulCodeCoreOperationSolution
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.CoreOperation.Test", "See package version number")]
    internal
#else
    public
#endif
    class CoreOperationDummyFactory : DefaultCoreOperationDummyFactory
    {
        public CoreOperationDummyFactory()
        {
            /* Add any overriding or custom registrations here. */
        }
    }
}